config/routes.rb
Rails.application.routes.draw do
  # get 'invoices/new'

  #  get 'static/non_supported'

  get 'static/contact_us'

  get 'static/bc_instructions'

  #---- Website Root -----------------------------------------------------------
  root 'home#index'
  get 'home/index'
  post 'home/set_panel_state'
  #  post 'home/acknowledge_bc_instructions'

  get 'welcome/index'

  get 'other_resources/index'
  #  get 'my_profile/index'
  get 'my_profile/edit'
  patch 'my_profile/update'
  put 'my_profile/update'

  devise_for :users

  get 'forms', to: 'forms#index'

  # A route to support the query of RTPs that match a new or existing invoice.
  # It has to be before the rest of the routes for invoices.
  get 'invoices/rtps'

  resources :funded_people, shallow: true do
    get :all_forms
    #    get :all_invoices
    resources :cf0925s
    resources :invoices
    resources :filled_in_forms
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  include Helpers::FiscalYear

  # One record for each address
  # ----- Associations ---------------------------------------------------------
  belongs_to :funded_person
  # belongs_to :cf0925, optional: true, inverse_of: :invoices
  has_many :invoice_allocations, inverse_of: :invoice, dependent: :destroy
  accepts_nested_attributes_for :invoice_allocations, allow_destroy: true
  has_many :cf0925s, through: :invoice_allocations, autosave: true

  #-----------------------------------------------------------------------------
  # ----- validations ----------------------------------------------------------
  # validate :validate_check_fy_on_service_dates, on: :complete
  # validate :validate_invoice_date_after_service_end, on: :complete
  validates :invoice_amount, presence: true, on: :complete
  validates :invoice_from, presence: true, on: :complete
  validate :validate_dates, on: :complete
  # validate :validate_service_start_before_service_end, on: :complete
  # validates :invoice_date, presence: { in: true, message: 'Invoice date required' }, on: :complete
  #  validates :service_start, presence: { in: true, message: 'Service provider defined, no service start date' }, on: :complete, unless: 'service_provider_name.blank?'
  #  validates :service_end, presence: { in: true, message: 'Service provider defined, no service end date' }, on: :complete, unless: 'service_provider_name.blank?'

  #-----------------------------------------------------------------------------
  # ----- Callbacks ------------------------------------------------------------
  #-----------------------------------------------------------------------------

  # ----- Public Methods -------------------------------------------------------
  ##
  # Allocate one or more RTPs to the invoice.
  def allocate(matches)
    matches = [matches] unless matches.respond_to?(:each)
    #  puts "allocate: matches #{matches.size}"
    incoming_set = matches.to_set
    old_set = invoice_allocations.to_set
    to_be_deleted_set = old_set - incoming_set
    # old_set = invoice_allocations.map do |ia|
    #   Match.new(ia)
    # end.to_set

    # puts "allocate: old_set #{old_set.map(&:object_id)}"
    # puts "allocate: incoming_set #{incoming_set.map(&:object_id)}"
    # puts "allocate: old_set + incoming_set #{(old_set + incoming_set).map(&:object_id)}"
    # puts "allocate: to_be_deleted_set #{(to_be_deleted_set).map(&:object_id)}"
    # puts "allocate: to_be_deleted_set classes #{(to_be_deleted_set).map(&:class)}"

    # puts "allocate: to_be_deleted_set #{(to_be_deleted_set).to_a}"
    invoice_allocations.delete(to_be_deleted_set.to_a).each do |ia|
      ia.cf0925.invoice_allocations.delete(ia)
    end
    # puts "allocate: invoice_allocations #{invoice_allocations.map(&:object_id)}"

    new_set = incoming_set - old_set
    # puts "----------------------------"
    # puts "invoice#allocate #{__LINE__}: For Invoice object_id: #{self.object_id} (#{self.invoice_amount})"
    # incoming_set.each {|s| puts " incoming: object_id: #{s.object_id} rtp id: #{s.cf0925.object_id} rtp db id: #{s.cf0925.id}  type: #{s.cf0925_type}"}
    # old_set.each {|s| puts " old: object_id: #{s.object_id} rtp id: #{s.cf0925.object_id}  rtp db id: #{s.cf0925.id}  type:  #{s.cf0925_type}"}
    # new_set.each {|s| puts " new: object_id: #{s.object_id} rtp id: #{s.cf0925.object_id}  rtp db id: #{s.cf0925.id}  type: #{s.cf0925_type}"}
    # (old_set - incoming_set).each {|s| puts " old - incoming: object_id: #{s.object_id} rtp id: #{s.cf0925.object_id}  rtp db id: #{s.cf0925.id}  type: #{s.cf0925_type}"}
    #    puts "allocate: incoming_set #{new_set.map(&:object_id)}"
    # puts "----------------------------"
    new_set.map do |match|
      connect(match.cf0925, match.cf0925_type)
    end

    # puts "allocate: result #{invoice_allocations.map(&:cf0925).map(&:object_id)}"
    # puts "allocate: result.inspect #{invoice_allocations.inspect}"

    invoice_allocations
  end

  ##
  # Put an invoice allocation between a cf0925 and an invoice.
  # Public so it can be used to set up test data.
  def connect(cf0925, type, amount = 0)
    invoice_allocations <<
      (ia = cf0925.invoice_allocations.build(cf0925_type: type, amount: amount))
    ia
  end

  def include_in_reports?
    valid?(:complete)
  end

  # ##
  # # Convert the three old invoice fields to the new unified field.
  # def invoice_from
  #   invoice_from = []
  #   invoice_from << service_provider_name if service_provider_name.present?
  #   invoice_from << agency_name if agency_name.present?
  #   invoice_from << supplier_name if supplier_name.present?
  #   return 'No Invoicee Defined' if invoice_from.empty?
  #   invoice_from.join(' / ')
  # end

  ##
  # Return an array of RTPs that could cover this invoice.
  # Doesn't consider how much has been spent.
  # Uses dates and matching criteria.
  def match
    # puts "In match child: #{funded_person.inspect}"
    return [] unless funded_person && funded_person.cf0925s
    # puts "ATTRIBUTES: #{attributes}"
    funded_person.match(attributes)
  end

  ##
  # Calculate out of pocket expenses for this invoice.
  def out_of_pocket
    return 0 unless invoice_amount && invoice_allocations
    # puts "out_of_pocket invoice_amount: #{invoice_amount}"
    # invoice_allocations
    #   .select(&:amount)
    #   .each { |ia| puts "out_of_pocket: #{ia.cf0925}, #{ia.invoice}, #{ia.cf0925_type}, #{ia.amount}" }
    [invoice_amount - invoice_allocations.select(&:amount).sum(&:amount), 0].max
  end

  ##
  # Return all the possible payees for an invoice.
  def possible_payees
    funded_person.possible_payees
  end

  # Return a range of the service start and end
  def service_period
    Range.new(service_start, service_end) if service_start && service_end
  end

  def start_date
    st = service_end
    st = invoice_date unless invoice_date.blank?
    st = service_start unless service_start.blank?
    st
  end #-- start_date --

  def validate_dates
    if service_start.blank? && invoice_date.blank? && service_end.blank?
      errors.add(:service_start, "must supply at least one date")
      errors.add(:service_end, "must supply at least one date")
      errors.add(:invoice_date, "must supply at least one date")
    end

    unless service_start.blank? || service_end.blank? || service_end >= service_start
      errors.add(:service_end, "service end cannot be earlier than service start")
    end

    unless service_start.blank? || service_end.blank? || funded_person.fiscal_year(service_start) == funded_person.fiscal_year(service_end)
      errors.add(:service_end, "must be in the same fiscal year as service start")
    end
  end

  def xxvalidate_check_fy_on_service_dates
    #-- run validation only if both dates are present
    return if service_start.blank? || service_end.blank?

    #-- Check that the invoice date is later than the service end date
    res = funded_person.fiscal_year(service_start).<=>funded_person.fiscal_year(service_end)
    errors.add(:service_end, "must be in the same fiscal year as service start") unless res == 0
  end #-- validate_check_fy_on_service_dates --

  def xxvalidate_invoice_date_after_service_end
    #-- run validation only if both dates are present
    return if invoice_date.blank? || service_end.blank?

    #-- Check that the invoice date is later than the service end date
    errors.add(:invoice_date, "should not be earlier than the service end") if
      service_end > invoice_date
  end #-- validate_invoice_date_after_service_end --

  #  def validate_service_dates_present_if_service_provider
  #    #-- run validation only if service_provider_name is present
  #    return if service_provider_name.blank?
  #
  #    #-- Check that the invoice date is later than the service end date
  #    errors.add(:invoice_date, 'should not be earlier than the service end`') if
  #      service_end < invoice_date
  #  end

  def xxvalidate_service_start_before_service_end
    #-- run validation only if both dates are present
    return if service_start.blank? || service_end.blank?

    #-- Check that the service end date is later than the service start date
    errors.add(:service_end, "must be after service start date") if
      service_end < service_start
  end #-- validate_service_start_before_service_end --

  #-----------------------------------------------------------------------------
  # ----- Protected Methods ----------------------------------------------------

  #  protected

  #-----------------------------------------------------------------------------

  # ----- Private Methods ------------------------------------------------------
  #-----------------------------------------------------------------------------
  private
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def new
    @funded_person =
      current_user.funded_people.find(params[:funded_person_id])
    @invoice = @funded_person.invoices.build
    # @url = funded_person_invoices_path params[:funded_person_id]
    #    @invoice.funded_person = @funded_person =FundedPerson.find(params[:funded_person_id])
    #  @invoice.cf0925 = @cf0925 = Cf0925.find(params[:cf0925_id])
  end

  def index
    @funded_person = current_user.funded_people.find(params[:funded_person_id])
    # TODO: Make this more Railsy
    @invoices = Invoice.where("funded_person_id = #{@funded_person.id}")
    @title = "Invoices for #{@funded_person.my_name}"
    @subtitle = "#{@invoices.size} Invoices"
  end

  def edit
    # TODO: add test cases that this works for attaching the RTP to the invoice
    # @url = invoice_path params[:id]

    @invoice = current_user.invoices.find(params[:id])
    @invoice.valid?(:complete)
    # @funded_person = @invoice.funded_person
  end

  def update
    logger.debug { "**** invoices_controller raw params #{params.inspect}" }
    # TODO: add test cases that this works for attaching the RTP to the invoice
    @invoice = current_user.invoices.find(params[:id])
    logger.debug { "******Service Provider:  #{@invoice.service_provider_name}" }
    logger.debug { "**** invoices_controller update safe params: #{invoice_params.inspect}" }
    @invoice.update(invoice_params)
    @invoice.funded_person.selected_fiscal_year = @invoice.funded_person.fiscal_year(@invoice.start_date)
    #    redirect_to funded_person_invoices_path(@invoice.funded_person_id)
    redirect_to root_path, notice: "Invoice updated."
  end

  def destroy
    @invoice = current_user.invoices.find(params[:id])
    @funded_person = @invoice.funded_person
    @invoice.destroy
    # redirect_to funded_person_invoices_path(@funded_person.id)
    redirect_to root_path
  end

  def create
    logger.debug { "**** invoices_controller raw params #{params.inspect}" }
    @funded_person = current_user.funded_people.find(params[:funded_person_id])

    logger.debug { "**** invoices_controller create safe params: #{invoice_params.inspect}" }
    if @invoice = @funded_person.invoices.create(invoice_params)
      # puts @invoice.inspect
      @funded_person.selected_fiscal_year = @funded_person.fiscal_year(@invoice.start_date)
      #      redirect_to funded_person_invoices_path(@invoice.funded_person_id)
      redirect_to home_index_path, notice: 'Invoice saved.'
    else
      render "new"
    end
    @msg = "phil"
  end

  def rtps
    # puts "IN RTPS PARAMS: #{params.inspect}"
    # Remember that this could be called from new, so you don't enen have an
    # invoice yet. So make a throw-away invoice.
    # TODO: Review how this is done. I think I can do better.

    if params[:id].present?
      @invoice = current_user.invoices.find(params[:id])
    else
      @invoice = Invoice.new
      @invoice.funded_person =
        @funded_person = current_user.funded_people.find(params[:funded_person_id])
    end

    @invoice.assign_attributes(convert_search_params_to_create_params)

    #  puts "TEMPORARY INVOICE: #{@invoice.inspect}"

    @invoice.allocate(@invoice.match)
    helpers.bootstrap_form_for([@funded_person, @invoice],
      builder: AutismFundingFormBuilder) do |f|
      # puts "PARTIAL: #{render_to_string(partial: 'invoice_allocation_wrapper',
      #                                   locals: {
      #                                     collection: @invoice.allocate(@invoice.match),
      #                                     invoice_form: f
      #                                   },
      #                                   layout: !request.xhr?)}"
      render partial: "invoice_allocation_wrapper",
             locals: { invoice_form: f },
             layout: !request.xhr?
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:cf0925_id,
      :invoice_date,
      :service_start,
      :service_end,
      :invoice_from,
      :invoice_amount,
      :invoice_reference,
      :notes,
      invoice_allocations_attributes: [
        :cf0925_id,
        :cf0925_type,
        :id,
        :invoice_id,
        :amount
      ])
  end

  def convert_search_params_to_create_params
    # { invoice: params }.require(:invoice)
    params.permit(:cf0925_id,
      :invoice_date,
      :service_start,
      :service_end,
      :invoice_from,
      :funded_person_id)
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def prep_options(the_object = nil, add_ons = nil)
    ary = []

    ##-- Determine if there are any add ons, and if so add the_method
    if add_ons.respond_to?(:each)
      add_ons.each do |a|
        ary << a.to_s
      end
    elsif !add_ons.blank?
      ary << add_ons.to_s
    end

    ary += the_object.possible_payees

    ary
  end
end

app/views/invoices/_enter_invoice_form.html.erb
<div id="invoice">
  <%#= render partial: 'shared/flash_area', locals: { model: @cf0925 } %>

<%#= form_for([@funded_person,@invoice]) do |f| %>
<%= bootstrap_form_for([@funded_person, @invoice],
                       builder: AutismFundingFormBuilder) do |f| %>
  <%= f.hidden_field :funded_person_id %>
  <%= f.hidden_field :id %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">
        Service Provider, Invoice Amount, Service Dates
      </h3>
    </div>
    <div class="panel-body" style="margin: 8px;">
      <div class="row">
        <% opt_list = prep_options @invoice, ['-- Other Service Provider --'] %>
        <%= f.select :invoice_from,
                     opt_list,
                     {
                       label: 'Invoice From',
                       column_width: 10
                     } %>

        <%= f.currency_field(:invoice_amount, step: '.01', label: 'Amount', column_width: 2) %>
      </div>
      <div class="row">
        <%= f.date_field :service_start, label: 'Service Start', column_width: 3 %>
        <%= f.date_field :service_end, label: 'Service End', column_width: 3 %>
        <%= f.date_field :invoice_date, label: 'Invoice Date', column_width: 3 %>
        <%= f.text_field :invoice_reference, label: 'Invoice Reference', column_width: 3 %>
      </div>

<% #----- Pattern for checking layout (Diagnostic) ------------------------------- %>
        <div class="row">
          <% i = 100 # set i to 1 to show grids %>
          <% while i < 12 %>
            <div class="col-sm-1" style="background-color: blue; text-align: center; color: white;">
              <%= i %>
              <% i = i + 1 %>
            </div>
            <div class="col-sm-1" style="background-color: red; text-align: center; color: white;">
              <%= i %>
                <% i = i + 1 %>
            </div>
          <% end %>
        </div>
  <% # - end of the check pattern ----------------------------------------------%>

        <!-- <div class="row">
          <% opt_list = prep_options @invoice, ['- - Other Agency - -'] %>
          <%= f.select :agency_name,
                       opt_list,
                       {
                         label: 'Agency',
                         column_width: 6
                       },
                       { _width: 6 } %>

          <%#=  f.collection_select :agency_name, Cf0925.all, :agency_name, :agency_name,{prompt: 'None Selected', include_blank: '-- Other Agency --'},{class: 'form-control'}  %>
          <% opt_list = prep_options @invoice, ['- - Other Supplier - -'] %>
          <%= f.select :supplier_name,
                       opt_list,
                       {
                         label: 'Supplier',
                         column_width: 6
                       },
                       { mn_width: 6 } %>
          <%#= f.collection_select :supplier_name, Cf0925.all, :supplier_name, :supplier_name,{prompt: 'None Selected', include_blank: '-- Other Supplier --'},{class: 'form-control'} %>
        </div> -->

        <div class="row">
          <%= f.text_field :notes, { size: 100, label: 'Notes', column_width: 12 } %>
        </div>
      </div>
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          Assign Request to Pay
        </h3>
      </div>
      <div class="panel-body">
        <div class="col-md-12">
          <div class="table-responsive">
            <table class="table table-striped test-cf0925-table">
              <thead>
                <tr>
                  <td class="text-right">
                    Start Date
                  </td>
                  <td class="text-right">
                    End Date
                  </td>
                  <td>
                    Payee
                  </td>
                  <td class="text-right">
                    Amount of Request
                  </td>
                  <td class="text-right">
                    Amount Available
                  </td>
                  <td class="text-right">
                    Amount from This Invoice
                  </td>
                </tr>
              </thead>
              <tbody class="cf0925-list-replace">
                <%= render(partial: 'invoice_allocation_wrapper',
                           locals: { invoice_form: f }) %>
              </tbody>
              <tfoot>
                <tr>
                  <td class="text-right" colspan="5">Out of Pocket</td>
                  <td class="text-right">
                    <%= f.currency_field :out_of_pocket,
                                         hide_label: true,
                                         label: 'Out of Pocket',
                                         disabled: 'disabled' %>
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
    <%= f.submit 'Save' %>
    <%= f.button 'Reset', type: 'reset', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/invoices/_invoice_allocation.erb
<tr class="static-form-record test-cf0925-invoice-row">
  <td class="text-right">
    <%= invoice_allocation.cf0925.display_start_date.to_formatted_s(:iso8601) %>
  </td>
  <td class="text-right">
    <%= invoice_allocation.cf0925.display_end_date.to_formatted_s(:iso8601) %>
  </td>
  <td><%= invoice_allocation.cf0925.payee %></td>
  <td class="text-right">
    <%= number_to_currency(invoice_allocation.cf0925.requested_amount) %>
  </td>
  <td class="text-right">
    <input value="bogus" style="text-align: right"></input>
  </td>
</tr>

app/views/invoices/_invoice_allocation.html.erb
<tr class="static-form-record test-cf0925-invoice-row test-req-<%= invoice_allocation.requested_amount.to_i %>">
  <td class="text-right">
    <%= invoice_allocation.display_start_date.to_formatted_s(:iso8601) %>
  </td>
  <td class="text-right">
    <%= invoice_allocation.display_end_date.to_formatted_s(:iso8601) %>
  </td>
  <td><%= invoice_allocation.payee %></td>
  <td class="text-right">
    <%= number_to_currency(invoice_allocation.requested_amount, units: '') %>
  </td>
  <td class="text-right amount-available">
    <%= number_to_currency(invoice_allocation.amount_available, units: '') %>
  </td>
  <td class="text-right">
    <%= invoice_allocation_form.currency_field(:amount, hide_label: true) %>
    <%= invoice_allocation_form.hidden_field(:cf0925_id) %>
    <%= invoice_allocation_form.hidden_field(:cf0925_type) %>
    <%= invoice_allocation_form.hidden_field(:invoice_id) %>
    <%= invoice_allocation_form.hidden_field(:id) %>
    <%= invoice_allocation_form.hidden_field(:requested_minus_other_invoices,
                                             class: 'requested-minus-other-invoices') %>
  </td>
</tr>

app/views/invoices/_invoice_allocation_wrapper.html.erb
<% if invoice_form.object.invoice_allocations.empty? %>
  <%= content_tag(:tr,
        content_tag(:td,
                    'No RTPs match this invoice, ' \
                    'or you need to fill in more fields above ' \
                    'to retrieve RTPs ' \
                    'that provide funds for this invoice.',
                    colspan: 5)) %>
<% else %>
  <%= invoice_form.fields_for :invoice_allocations do |invoice_allocation| %>
    <%#= content_tag(:tr, content_tag(:td, "IA: #{invoice_allocation.object.inspect}")) %>
    <%= render(partial: 'invoice_allocation',
               object: invoice_allocation.object,
               locals: { invoice_allocation_form: invoice_allocation }) %>
  <% end %>
<% end %>

app/views/invoices/_invoices.html.erb
<div class="table-responsive">
  <table class="table table-striped invoice-list">
    <thead>
      <tr>
        <th class="text-center">Date</th>
        <th class="text-left">From</th>
        <th class="text-right">Amount</th>
        <th class="text-center">Status</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% if invoices.size == 0 %>
      <tr>
        <td colspan="5" class="text-center"><%= message_on_empty_report %></td>
      <% else %>
        <% invoices.sort{|x,y| (y.start_date || Date.new(1900,1,1)) <=> (x.start_date || Date.new(1900,1,1))}.each do |i| %>
        <tr>
          <td class="text-center">
            <%= i.start_date %>
          </td>
          <td>
            <%= i.invoice_from %>
          </td>
          <td class="text-right">
            <%= number_to_currency(i.invoice_amount, units: '') %>
          </td>
          <td class="text-center">
            <% if i.include_in_reports? %>
            Complete
          <% else %>
            Need More info
            <% end %>
          </td>
          <td class="text-center">
            <%= link_to('Edit', edit_invoice_path(i.id), class: "btn btn-xs btn-primary") %>
            <%#= link_to('Paid', '#', class: "btn btn-xs btn-primary", disabled: true) %>
            <%= link_to('Delete', invoice_path(i.id), method: :delete, data: { confirm: "\Are you really, really sure?\n\nThis action cannot be undone.\n\n"}, class: "btn btn-xs btn-danger") %>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot></tfoot>
  </table>
</div>

app/views/invoices/create.html.erb
I am the creator!

<br><br>
<div style="width: 60%; border: double 1pt red;">
  <br>
    All params: <%= debug(params) %>
  <br>
  <br>
    permitted: <%= debug(params.required(:invoice).permit(:funded_person_id, :service_start)) %>
  <br>

  <br>
    try: <%= debug(params.required(:invoice).permit(:funded_person_id, :service_start)) %>
  <br>

</div>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>
<br>
<%= render 'enter_invoice_form' %>

app/views/invoices/index.html.erb
<h3><%= @title %></h3>
<div style="font-size: 8pt"><%= @subtitle %></div>
<div class="col-md-1"></div>
<div class="col-md-10">
  <%= render partial: 'invoices', locals: { invoices: @invoices,  message_on_empty_report: 'You have not entered any invoices' } %>
<div class="col-md-1"></div>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>
<br>
<%= render 'enter_invoice_form' %>