config/routes.rb
Rails.application.routes.draw do
  # get 'invoices/new'

  #  get 'static/non_supported'

  get 'static/contact_us'

  get 'static/bc_instructions'

  #---- Website Root -----------------------------------------------------------
  root 'home#index'
  get 'home/index'
  post 'home/set_panel_state'
  #  post 'home/acknowledge_bc_instructions'

  get 'welcome/index'

  get 'other_resources/index'
  #  get 'my_profile/index'
  get 'my_profile/edit'
  patch 'my_profile/update'
  put 'my_profile/update'

  devise_for :users

  get 'forms', to: 'forms#index'

  # A route to support the query of RTPs that match a new or existing invoice.
  # It has to be before the rest of the routes for invoices.
  get 'invoices/rtps'

  resources :funded_people, shallow: true do
    get :all_forms
    #    get :all_invoices
    resources :cf0925s
    resources :invoices
    resources :filled_in_forms
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_if_can_see_my_home

  def check_if_can_see_my_home
    redirect_to my_profile_edit_path unless current_user.can_see_my_home?
  end

  def index
    @funded_people = current_user.funded_people
    @funded_people.each do |child|
      fy = params[:year][child.id.to_s]
      child.selected_fiscal_year = fy if fy
      logger.debug do
        "Child: #{child.my_name} " \
        "Fiscal year: #{fy} " \
        "Number of CF0925s: " \
        "#{child.cf0925s_in_selected_fiscal_year.size} " \
        "Number of invoices: " \
        "#{child.invoices_in_selected_fiscal_year.size}"
      end
    end if params[:year]
  end

  ##
  # Set the state of a panel on the index view
  def set_panel_state
    # puts "set panel state: #{params[:panel_state]}"
    child = FundedPerson.find(params[:funded_person_id])
    child.set_childs_panel_state(params[:panel_state])
    head :ok # , content_type: 'text/html'
    # render inline: ''
  end
end

app/views/home/_status.html.erb
<div class=row>
  <div class="col-md-2">Funding spent: $3,000</div>
  <div class="col-md-2">Funding committed but not spent: $1,000</div>
  <div class="col-md-2">Funding remaining this year: $2,000</div>
  <div class="col-md-2">
    Total funding for year: $6,000
  </div>
  <div class="col-md-2">
    Out of pocket: $0
  </div>
  <div class="col-md-2">
    <!-- TODO: Make the years do something. -->
    <!-- TODO: Hide the dropdown if there's only one year? -->
    <% if (fiscal_year_list = funded_person.fiscal_years).present? %>
      <%= select_tag "Year",
                     options_from_collection_for_select(fiscal_year_list,
                                                        :to_s,
                                                        :to_s,
                                                        fiscal_year_list.first.to_s),
                     class: "pull-right" %>
     <% end %>
  </div>
</div>

app/views/home/index.html.erb
<div id="home">
  <% title("All Children") %>
  <% unless current_user.can_create_new_rtp? %>
    <div class="alert alert-warning">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <span class="glyphicon glyphicon-star-empty"></span>
          The forms and funding found in this area are only availble to residents of
          British Columbia.
          <br>
          You are no longer a resident of British Columbia so you may not create new Request to Pay forms.
          However, you may continue to view and edit existing forms as well as create, edit and delete new
          invoices.
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  <% end %>
  <%= render 'shared/notifications' %>
  <%# The form has to go outside the accordion to get the "one tab open at a time"
      functionality to work. %>
  <%= form_tag(home_index_path, method: :get, class: "fiscal-year-selector") do %>
    <div class="panel-group accordion" id="accordion" aria-multiselectable="true">
      <%= render partial: "funded_people/show_panel", collection: @funded_people, as: :funded_person %>
    </div>
  <% end %>
</div>
<div class="text-info text-center">
  Click on My Profile if you wish to edit your profile information, add a funded child
  or modify a funded child's information.
</div>