config/routes.rb
Rails.application.routes.draw do
  # get 'invoices/new'

  #  get 'static/non_supported'

  get 'static/contact_us'

  get 'static/bc_instructions'

  #---- Website Root -----------------------------------------------------------
  root 'home#index'
  get 'home/index'
  post 'home/set_panel_state'
  #  post 'home/acknowledge_bc_instructions'

  get 'welcome/index'

  get 'other_resources/index'
  #  get 'my_profile/index'
  get 'my_profile/edit'
  patch 'my_profile/update'
  put 'my_profile/update'

  devise_for :users

  get 'forms', to: 'forms#index'

  # A route to support the query of RTPs that match a new or existing invoice.
  # It has to be before the rest of the routes for invoices.
  get 'invoices/rtps'

  resources :funded_people, shallow: true do
    get :all_forms
    #    get :all_invoices
    resources :cf0925s
    resources :invoices
    resources :filled_in_forms
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login

  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Autism Funding</h1>
    <p>
      This site helps you manage your autism funding.
      You can fill out forms,
      print them,
      and send them to the Ministry.
      Then you can easily track
      how much you've committed,
      and how much you've spent.
    </p>
    <p>
      We're just getting started.
      Our first goal is to support parents
      and care-givers
      in the province of British Columbia.
      We hope to support other provinces in the future.
    </p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>For Parents and Care Givers</h2>
      <p>
        Keep track of how much of your funding
        you've committed,
        how much has actually been spent,
        and how much you have to left to spend.
        Estimate when you'll run out of funding,
        to help you budget for those parts of the year
        where you might have to pay out of pocket.
      </p>
      <p>
        <%= link_to "Sign Up", new_user_registration_path %>
        now to start using the site, or
        <%= link_to "Log in", new_user_session_path %>
        if you are already a registered user of our site.
      </p>
      <p>
        <%= link_to "Contact Us", static_contact_us_path %>
        with your questions, ideas, and feedback on this site.
      </p>
    </div>
    <div class="col-md-6">
      <h2>For Service Providers</h2>
      <p>
        Right now, our application is targeted at helping families and care
        givers, but, if demand drives us, we'd like to extend our application
        so that we can help Service Providers.  This application could allow you
        to see how much funding you're approved for,
        so you can help your families stay up-to-date
        with their funding applications,
        meaning fewer delays in paying your invoices.
      </p>
      <p>
        <%= link_to "Sign Up", new_user_registration_path %>
        if you'd like to explore the capabilites of this
        site.
      </p>
      <p>
        <%= link_to "Contact Us", static_contact_us_path %>
        with your thoughts and suggestions as to how we could
        extend our application to help Service Providers as well
        as families.
      </p>
    </div>
  </div>
</div>