config/routes.rb
Rails.application.routes.draw do
  # get 'invoices/new'

  #  get 'static/non_supported'

  get 'static/contact_us'

  get 'static/bc_instructions'

  #---- Website Root -----------------------------------------------------------
  root 'home#index'
  get 'home/index'
  post 'home/set_panel_state'
  #  post 'home/acknowledge_bc_instructions'

  get 'welcome/index'

  get 'other_resources/index'
  #  get 'my_profile/index'
  get 'my_profile/edit'
  patch 'my_profile/update'
  put 'my_profile/update'

  devise_for :users

  get 'forms', to: 'forms#index'

  # A route to support the query of RTPs that match a new or existing invoice.
  # It has to be before the rest of the routes for invoices.
  get 'invoices/rtps'

  resources :funded_people, shallow: true do
    get :all_forms
    #    get :all_invoices
    resources :cf0925s
    resources :invoices
    resources :filled_in_forms
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/my_profile_controller.rb
class MyProfileController < ApplicationController
  def index
    set_objects
  end

  def edit
    current_user.assign_attributes(user_params) unless params[:user].nil?
    # set_objects
    @warning = nil
    unless current_user.valid?
      @warning = "Your information cannot be saved until you have corrected the information highlighted below"
    end
    # Ensure there is always one new funded person that can be filled in
    # TODO: I didn't realize you could use new this way.
    current_user.funded_people.new
  end

  # def help_pip(line)
  #   cnt = 0
  #   current_user.funded_people.each do |fp|
  #     unless fp.id.nil?
  #       cnt += 1
  #     end
  #   end
  #   logger.debug "#{Time.now.strftime('%H:%M:%S.%L')}  #{line}: size: #{current_user.funded_people.size}  real: #{cnt}   :xbyk----"
  # end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      redirect_to my_profile_edit_path(request.parameters)
    end
  end

  #   def add_to_flash(from_whence)
  #     flash[:save_errors] || flash[:save_errors] = "---- Start----"
  #     flash[:save_errors] += "<br><br>Hit Update from #{from_whence}"
  #     flash[:save_errors] += "<br><b>current_user.valid?:</b> [#{current_user.valid?}]"
  #     # flash[:save_errors] += "<br><b>current_user.errors.messages.size:</b> [#{current_user.errors.messages.size}]"
  #     flash[:save_errors] += "<br><b>current_user.funded_people.size:</b> [#{current_user.funded_people.size}]"
  # #    flash[:save_errors] += "<br><b>params[:user][:addresses_attributes]['0'].as_json:</b> [#{params[:user][:addresses_attributes]['0'].as_json}]"
  # #    flash[:save_errors] += "<br><b>user_params[:user][:phone_numbers_attributes]['0'].as_json:</b> [#{user_params[:user][:phone_numbers_attributes]['0'].as_json}]"
  #     # the_hash = user_params
  # #    the_hash['phone_numbers_attributes']['0'].each do |key|
  # #      flash[:save_errors] += " <u> #{key} </u>"
  # #    end
  # #    flash[:save_errors] += "<br><b>the_hash['phone_numbers_attributes']['0'].as_json:</b> [#{the_hash['phone_numbers_attributes']['0'].as_json}]"
  # #    flash[:save_errors] += "<br><b>params[:user][:phone_numbers_attributes]['1'].as_json:</b> [#{params[:user][:phone_numbers_attributes]['1'].as_json}]"
  # #    tmp = current_user.phone_numbers[0]
  # #    flash[:save_errors] += "<br><b>From current_user:</b>  id: #{tmp.id} type: #{tmp.phone_type} number: #{tmp.phone_number}"
  #
  #   end

  def x_update
    flash[:save_errors] = nil
    set_objects
    #    add_data_for_user

    if flash[:save_errors].nil?
      # redirect_to my_profile_index_path(request.parameters)
      #  redirect_to root_path
      redirect_to my_profile_edit_path(request.parameters)
    else
      redirect_to my_profile_edit_path(request.parameters)
    end
  end

  #-- Private Methods -----------------------------------------------

  private

  def user_params
    params.require(:user).permit(:name_first, :name_middle, :name_last, :address, :city, :postal_code, :province_code_id, :home_phone_number, :work_phone_number, :work_phone_extension, funded_people_attributes: [:id, :name_first, :name_middle, :name_last, :birthdate, :child_in_care_of_ministry, :_destroy])
  end

  def xadd_flash(the_group, the_message)
    if flash[:save_errors].nil?
      flash[:save_errors] = "<u>Please Correct the Following and Re-Save</u><br><br>"
    else
      flash[:save_errors] += "<br>"
    end
    flash[:save_errors] += "#{the_group}: #{the_message}"
  end
end

app/helpers/my_profile_helper.rb
module MyProfileHelper
end

app/views/my_profile/edit.html.erb
<div class="container">
  <h1>Edit My Data</h1>
  <br>
  <% if current_user.missing_key_info? %>
    <div class="alert alert-warning">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <span class="glyphicon glyphicon-star-empty"></span>
          To begin taking advantage of the functionality of this site you must
          enter the province of your address as well as at least one funded child
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  <% end %>
  <% unless current_user.bc_resident? %>
    <div class="alert alert-warning">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <span class="glyphicon glyphicon-star-empty"></span>
          The forms and funding found in this area are only availble to residents of
          British Columbia.
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  <% end %>

  <% unless @warning.nil? %>
    <div class="alert alert-danger">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <%= @warning.html_safe %>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  <% end %>

  <%= bootstrap_form_for current_user, builder: AutismFundingFormBuilder, url: my_profile_update_path do |the_form| %>

    <%= panel the_form, "Edit User Information" do |p| %>
      <%= form_row do %>
        <%= the_form.text_field(:name_first, column_width: 3, label: 'First') %>
        <%= the_form.text_field(:name_middle, column_width: 3, label: 'Middle') %>
        <%= the_form.text_field(:name_last, column_width: 3, label: 'Last') %>
      <% end %>
      <%= form_row do %>
        <%= the_form.text_field(:address, column_width: 6, label: 'Address') %>
      <% end %>
      <%= form_row do %>
        <%= the_form.text_field(:city, column_width: 6, label: 'City') %>
        <%= the_form.collection_select :province_code_id, ProvinceCode.all, :id, :province_name, {column_width: 3, label: 'Province', prompt: true} %>
        <%= the_form.postal_code_field(:postal_code, column_width: 3, label: 'Postal Code') %>
      <% end %>
      <%= form_row do %>
        <%= the_form.phone_field :home_phone_number, column_width: 3, label: 'Home Phone' %>
        <%= the_form.phone_field :work_phone_number, column_width: 3, label: 'Work Phone' %>
        <%= the_form.text_field :work_phone_extension, column_width: 2, label: 'Extension' %>
      <% end %>
    <% end %>
    <%= panel the_form, "Funded Children" do |p| %>
      <%= the_form.fields_for :funded_people do |fp| %>
        <% if fp.object.id.nil? %>
          <%= form_row do %>
            <div class="col-md-12 text-center mark">
              Add a new funded child by entering data below
            </div>
          <% end %>
        <% end %>
        <%= form_row do %>
          <%= fp.text_field(:name_first, column_width: 3, label: 'First Name') %>
          <%= fp.text_field(:name_middle, column_width: 3, label: 'Middle') %>
          <%= fp.text_field(:name_last, column_width: 3, label: 'Last') %>
          <%= fp.date_field(:birthdate, column_width: 2, label: 'Birthdate') %>
          <% unless fp.object.id.nil? %>
            <%= fp.check_box :_destroy, column_width: 1, label: 'Delete?' %>
          <% end %>
          <br><br>
        <% end %>
        <%= form_row do %>
          <div class="col-md-1">
          </div>
          <%= fp.form_group :child_in_care_of_ministry,  {label: {text: 'Is this child in the care of the ministry ?'}, column_width: 4, inline: true}  do %>
            <%= fp.radio_button(:child_in_care_of_ministry, 'true', label: "Yes", inline: true) %>
            <%= fp.radio_button(:child_in_care_of_ministry, 'false', label: "No", inline: true) %>
          <% end %>
          <div class="col-md-3">
            <%# coll = Array[{text: 'Yes', val: true },{text: 'No', val: false }] %>
            <%#= fp.collection_radio_buttons(:child_in_care_of_ministry, coll, :val, :text, label: 'Child in Care of Ministry?') %>
          </div>
        <% end %>
        <br><br>
      <% end %>
    <% end %>

    <%= form_row do %>
      <div class="col-md-12 lead">
        <%= the_form.submit class: 'btn btn-primary' %>
        <%= the_form.button 'Reset', type: 'reset', class: 'btn btn-primary' %>
      </div>
    <% end %>
  <% end %>
</div>